version: '3'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
    ports:
      - "5432:5432"
  temporal:
    image: temporalio/server:0.23.1
    ports:
     - "7233:7233"
    environment:
      - "DB=postgres"
      - "DB_PORT=5432"
      - "POSTGRES_USER=temporal"
      - "POSTGRES_PWD=temporal"
      - "POSTGRES_SEEDS=postgreschicken"
      - "DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml"
    depends_on:
      - postgres
  temporal-admin-tools:
    image: markmark206/admin-tools:9f73a263908bc8fa7ea020c4458b9a0135be0d50
    stdin_open: true
    tty: true
    environment:
      - "TEMPORAL_CLI_ADDRESS=temporal:7233"
    depends_on:
      - temporal
